-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
--
-- Add any additional autocmds here
-- with `vim.api.nvim_create_autocmd`
--
-- Or remove existing autocmds by their group name (which is prefixed with `lazyvim_` for the defaults)
-- e.g. vim.api.nvim_del_augroup_by_name("lazyvim_wrap_spell")

-- Workaround for autocmd tab key function params 
--local luasnip = require('luasnip')
--
--vim.api.nvim_create_autocmd("ModeChanged", {
--  group = vim.api.nvim_create_augroup("UnlinkLuaSnipSnippetOnModeChange", {
--    clear = true,
--  }),
--  pattern = { "s:n", "i:*" },
--  desc = "Forget the current snippet when leaving the insert mode",
--  callback = function(evt)
--    -- If we have n active nodes, n - 1 will still remain after a `unlink_current()` call.
--    -- We unlink all of them by wrapping the calls in a loop.
--    while true do
--      if luasnip.session and luasnip.session.current_nodes[evt.buf] and not luasnip.session.jump_active then
--        luasnip.unlink_current()
--      else
--        break
--      end
--    end
--  end,
--})

